apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.11.7
apiServerCertSANs:
- k8s-master01
- k8s-master02
- k8s-master03
- k8s-master-lb
- 192.168.40.189
- 192.168.40.190
- 192.168.40.191
- 192.168.40.193
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://192.168.40.189:2379"
      advertise-client-urls: "https://192.168.40.189:2379"
      listen-peer-urls: "https://192.168.40.189:2380"
      initial-advertise-peer-urls: "https://192.168.40.189:2380"
      initial-cluster: "k8s-master01=https://192.168.40.189:2380"
    serverCertSANs:
      - k8s-master01
      - 192.168.40.189
    peerCertSANs:
      - k8s-master01
      - 192.168.40.189
networking:
  # This CIDR is a Calico default. Substitute or remove for your CNI provider.
  podSubnet: "10.244.0.0/16"
